---
# This playbook configure hosts: initial configuration, installing docker on DO hosts

- hosts: dockerhosts
  name: create a droplet
  tags:
      - create_droplet
      - essential


  roles:
    - {role: droplet, tags: ["create_droplet"]}

- name: enabling ssh and check the server configuration
  hosts: dockerhosts
  tags:
    - essential
  vars:
      local_known_hosts_file: "~/.ssh/known_hosts"


  roles:
    - { role: ssh_port_detect, tags: ["hostcheck", "ssh_port_detect"] }
    - { role: known_hosts, tags: ["hostcheck", "known_hosts"] }
    - { role: ssh_user_detect, tags: ["hostcheck", "ssh_user_detect"] }

- name: adding the droplet to a virtual hosts file fro host configuration
  hosts: dockerhosts
  tags:
    - essential
  tasks:
  - add_host:
     name: "{{ droplet_details.droplet.ip_address }}"
     groups: new_droplet
     do_host_user: "{{do_host_user}}"
     do_host_ssh_port: "{{do_host_ssh_port}}"
     public_key: "{{public_key}}"
     custom_user: "{{custom_user}}"
     custom_ssh_port: "{{custom_ssh_port}}"

- name: Wait for system to become reachable
  tags:
      - wait_host_reachable
  hosts: new_droplet
  gather_facts: no
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - raw: test -e /usr/bin/pip || (apt -y update && apt install -y python-pip)
  vars:
      ansible_user: "{{do_host_user}}"
      ansible_port: "{{do_host_ssh_port}}"
  tasks:
  - name: wait_timeout
    wait_for_connection:
     delay: 60
     timeout: 300


- name : configure the server
  tags:
      - configure_server
  hosts: new_droplet
  become: true
  vars:
      ansible_user: "{{do_host_user}}"
      ansible_port: "{{do_host_ssh_port}}"
      do_host_ip: "{{inventory_hostname}}"

  roles:
    - { role: ufw, tags: ["hostconfig", "ufw"] }
    - { role: deroot, tags: ["hostconfig", "deroot"] }
    - { role: ssh_user_detect, tags: ["hostconfig", "ssh_user_detect"] }
    - { role: swap, tags: ["hostconfig", "swap"] }
    - { role: docker, tags: ["hostconfig", "docker"] }
    - { role: fail2ban, tags: ["hostconfig", "fail2ban"] }


#     - { role: python, tags: ["hostconfig","python"] }
#     - { role: sshd, tags: ["hostconfig", "sshd"] }
