# Ensure a droplet is present
# If droplet id already exist, will return the droplet details and changed = False
# If no droplet matches the id, a new droplet will be created and the droplet details (including the new id) are returned, changed = True.

- digital_ocean:
    state: present
    command: droplet
    name: "{{ansible_host}}"
    unique_name: yes
    size_id: 512mb
    region_id: sgp1
    image_id: docker-16-04
    wait_timeout: 500
    ssh_key_ids: 741976
    api_token: "{{api_token}}"
  register: droplet_details

- debug: msg="IP is {{ droplet_details.droplet.ip_address }}"

- name: set do_host_ip
  set_fact: do_host_ip={{droplet_details.droplet.ip_address}}

# - wait_for:
#     host: "{{ droplet_details.droplet.ip_address }}"
#     port: 2375
#     delay: 10
