
- name: create a custom user
  user: name="{{custom_user}}" shell=/bin/bash groups=admin,docker,sudo append=yes

- name: add new public key to authorized key for custom_user
  authorized_key: user="{{custom_user}}" key="{{ public_key }}"


- name: disable root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin yes"  line="PermitRootLogin no" state=present

- name: disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" insertafter="^#PasswordAuthentication" line="PasswordAuthentication no"

- name: passwordless sudo
  lineinfile: dest=/etc/sudoers regexp='^%sudo' line="%sudo ALL=(ALL) NOPASSWD:ALL"


- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for host={{ inventory_hostname }} port={{do_host_ssh_port}} delay=90 timeout=300
  become: false
